version: 0.1

environment_variables:
  plaintext:
    DJANGO_SETTINGS_MODULE: config.settings.test
    SECRET_KEY: nosecret
    DATABASE_DEFAULT_URL: sqlite:///db1.sqlite3
    DATABASE_STREAMDATA_URL: sqlite:///db2.sqlite3
    STREAM_INCOMING_PRIVATE_KEY: changeme
    STREAM_INCOMING_PUBLIC_KEY: changeme
    GOOGLE_API_KEY: changeme
    OPBEAT_ENABLED: False

phases:
  pre_build:
    commands:
      - echo Prebuild ops
      - pip3 install -r requirements.txt

  build:
    commands:
      - echo Building the application

  post_build:
    commands:
      - echo Build completed on `date`

      # Ensure the nginx sites-available directory exists
      - echo "Checking if /etc/nginx/sites-available exists and creating if necessary..."
      - sudo mkdir -p /etc/nginx/sites-available

      # Remove the existing symlink if it exists
      - echo "Checking if symlink exists and removing it..."
      - if [ -L /etc/nginx/sites-enabled/EcommerceApplication ]; then sudo rm /etc/nginx/sites-enabled/EcommerceApplication; fi

      # Copy the nginx configuration from the correct path
      - echo "Copying nginx configuration..."
      - sudo cp nginx/nginx.conf /etc/nginx/sites-available/EcommerceApplication

      # Create the symbolic link
      - echo "Creating symbolic link..."
      - sudo rm -rf /etc/nginx/sites-enabled/EcommerceApplication
      - sudo mkdir -p /etc/nginx/sites-enabled
      - sudo ln -s /etc/nginx/sites-available/EcommerceApplication /etc/nginx/sites-enabled/
      # Reload nginx
      - echo "Reloading Nginx..."
      - sudo systemctl reload nginx

artifacts:
  files:
    - '**/*'


